### PR TITLE
Added banktransfer and added nuget package for Newtonsoft.Json

### PR DESCRIPTION
**Pull request by mwillebrands**

### CODE REVIEW

**Comment by sebastianberm** [comment]
Code is looking okay :).
At the moment, we're working on a few modifications, so we'll merge this when that's ready.
We will also update the nuget package at that time.

Thank you for the contribution!

**Comment by sebastianberm** [comment]
Today, we have completed the demo app. I have merged the code, and we'll do a new release in the next couple of days to include this.
Can I ask why you needed this particular API? - As the refund api might be more interesting for you (perhaps).

**Comment by mwillebrands** [comment]
We needed to do banktransfers to our clients, and refunds sounds different. The api doc doesn't seem to contain any differences between those two, so i just chose the one with the correct name.

**Comment by sebastianberm** [comment]
Hi Maarten,
You probably want to do this:
* Use the API with payment method 136 (bank transfer)

If you provide the e-mailaddress and order dataset, and if you use the SendConfirmMail from my last commit a couple of days ago, Pay.nl will automatically e-mail your clients the data as well, as provide you with a normal URL to redirect the user to.

I think this will do exactly what you wanted. (If you don't need the SendConfirmMail, you can just use the version that's currently released, otherwise, we need to release the new version first.)

**Comment by mwillebrands** [comment]
Hi Sebastian,

I'm already using the banktransfer and it works like a charm ;)
We already know the banknumber of our clients, so there's no need for customer interaction.

Yours,
maarten

**Pull request merged**
