### PR TITLE
Update lower tax class to 9%

### PR DESCRIPTION
**Pull request by max-geraci**

### CODE REVIEW

**Comment by abelbraaksma** [comment]
Related, fixes: #25.

**Comment by sebastianberm** [comment]
Hi Abel,
I do not agree with you as this only applies to new orders, existing orders will already contain the correct values returned by the API.
So I think it would be safe to merge this, as I believe the admin will just say if it's high or low, and not the actual value.

@woutse : Can you confirm this?

**Comment by abelbraaksma** [comment]
> existing orders will already contain the correct values returned by the API.

@sebastianberm but if you retrieve such existing orders from Pay.nl, how can the api wrapper distinguish between 6% and 9%? Or will a historic order match as 9%, and we need to correct this based on the date of the order (hacky)? Or, since it is an enum, just cast it to an int, because '6' will be in it, but won't match any of the enum values (allowed in C#)?

Bottom line, the question is: in a mixed set of orders with 6% and 9%, how is this expected to work unambiguously?

**Comment by KreativJos** [comment]
It seems wrong to me to have the enum values set at the percentages used in Dutch law. There could be some sort of mapping for this.

**Pull request closed without merging**
